name: Validação

on:
  push:
    paths:
      - 'datapackage.yaml'
      - 'schemas/*'
      - 'README.md'
      - 'CHANGELOG.md'
      - 'CONTRIBUTING.md'
      - 'data/*'
      
jobs:
  validate:
  # this workflow will automate datapackage validation with frictionless
  # for more information see: https://repository.frictionlessdata.io/
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Validate data
        uses: frictionlessdata/repository@v1
